apiVersion: v2
appVersion: v1.32.0
description: A self-hosted data logger for your Tesla 🚘
name: teslamate
version: v0.1
keywords:
  - teslamate
  - tesla
home: https://github.com/nidr0x/teslamate-helm-chart
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tesla_Motors.svg/793px-Tesla_Motors.svg.png
sources:
  - https://github.com/teslamate-org/teslamate
maintainers:
  - name: Carlos Rodríguez
    email: nidr0x@gmail.com
dependencies:
  - name: grafana
    version: 8.8.2
    repository: https://grafana.github.io/helm-charts
